"use client";
import Link from "next/link";
import { useState } from "react";
import { Database, FileText, Mail, MapPin, Plug } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui";
import { TenantGmailConnection } from "./tenant-gmail-connection";
import { TenantWorkspaceSettingsForm } from "./tenant-workspace-settings-form";
import { cn } from "@/lib/utils";

const tabs = [{ key: "sender", label: "Sender & general", icon: Mail }, { key: "templates", label: "Email templates", icon: FileText }, { key: "territories", label: "Territories", icon: MapPin }, { key: "gmail", label: "Gmail", icon: Plug }, { key: "data", label: "Data", icon: Database }] as const;
export function TenantSettingsTabs({ settings, connection, products, territories, stats }: { settings: { sender_name: string; sender_company: string; sender_email: string; sender_signature: string; daily_lead_target: number }; connection: { status: string; connected_email: string } | null; products: Array<{ id: string; name: string }>; territories: Array<{ id: string; town: string; country: string; active: boolean }>; stats: { leads: number; content: number; media: number } }) { const [tab, setTab] = useState<(typeof tabs)[number]["key"]>("sender"); return <div className="grid gap-6 lg:grid-cols-[200px_1fr]"><nav className="flex gap-1 overflow-x-auto lg:flex-col">{tabs.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setTab(key)} className={cn("flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium", tab === key ? "bg-accent-soft text-accent" : "text-muted hover:bg-surface2 hover:text-ink")}><Icon className="h-4 w-4" />{label}</button>)}</nav><div>{tab === "sender" && <Card><CardHeader><CardTitle className="text-success">Sender identity & general</CardTitle></CardHeader><CardContent><TenantWorkspaceSettingsForm settings={settings} /></CardContent></Card>}{tab === "gmail" && <Card><CardHeader><CardTitle className="text-success">Gmail connection</CardTitle></CardHeader><CardContent><TenantGmailConnection connection={connection} /></CardContent></Card>}{tab === "templates" && <Card><CardHeader><CardTitle className="text-success">Email templates</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted">Templates are stored per project so sales copy never crosses product boundaries.</p>{products.map((product) => <Link key={product.id} className="block rounded-lg border p-3 text-sm font-medium text-ink hover:bg-surface2" href={`/app/products/${product.id}`}>{product.name} <span className="text-muted">— edit templates</span></Link>)}</CardContent></Card>}{tab === "territories" && <Card><CardHeader><CardTitle className="text-success">Territories</CardTitle></CardHeader><CardContent className="space-y-2">{territories.map((territory) => <div key={territory.id} className="rounded-lg border p-3 text-sm"><span className="font-medium text-ink">{territory.town}, {territory.country}</span><span className="ml-2 text-muted">{territory.active ? "Active" : "Inactive"}</span></div>)}{!territories.length && <p className="text-sm text-muted">No territories yet. Add one from the Sales Agent.</p>}</CardContent></Card>}{tab === "data" && <Card><CardHeader><CardTitle className="text-success">Workspace data</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-4 text-center">{[["Leads", stats.leads], ["Content", stats.content], ["Media", stats.media]].map(([label, value]) => <div key={String(label)}><p className="text-2xl font-semibold text-ink-strong">{value}</p><p className="text-xs text-muted">{label}</p></div>)}</CardContent></Card>}</div></div>; }
