"use client";
import { useState } from "react";
import { CreditCard, MapPin, Plug } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui";
import { TenantGmailConnection } from "./tenant-gmail-connection";
import { TenantTerritorySettings } from "./tenant-territory-settings";
import { cn } from "@/lib/utils";

const tabs = [{ key: "gmail", label: "Gmail", icon: Plug }, { key: "territories", label: "Territories", icon: MapPin }, { key: "billing", label: "Billing & usage", icon: CreditCard }] as const;
export function TenantSettingsTabs({ connection, products, territories, usage }: { connection: { status: string; connected_email: string } | null; products: Array<{ id: string; name: string }>; territories: Array<{ id: string; town: string; country: string; active: boolean }>; usage: { salesRuns: number; leadsFound: number; contentItems: number } }) { const [tab, setTab] = useState<(typeof tabs)[number]["key"]>("gmail"); return <div className="grid gap-6 lg:grid-cols-[200px_1fr]"><nav className="flex gap-1 overflow-x-auto lg:flex-col">{tabs.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => setTab(key)} className={cn("flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium", tab === key ? "bg-accent-soft text-accent" : "text-muted hover:bg-surface2 hover:text-ink")}><Icon className="h-4 w-4" />{label}</button>)}</nav><div>{tab === "gmail" && <Card><CardHeader><CardTitle className="text-success">Gmail connection</CardTitle></CardHeader><CardContent><TenantGmailConnection connection={connection} /></CardContent></Card>}{tab === "territories" && <Card><CardHeader><CardTitle className="text-success">Territories</CardTitle></CardHeader><CardContent><TenantTerritorySettings territories={territories} hasProducts={products.length > 0} /></CardContent></Card>}{tab === "billing" && <BillingUsage usage={usage} />}</div></div>; }

function BillingUsage({ usage }: { usage: { salesRuns: number; leadsFound: number; contentItems: number } }) {
  const stats = [{ label: "Sales Agent runs", value: usage.salesRuns }, { label: "Leads found", value: usage.leadsFound }, { label: "Content created", value: usage.contentItems }];
  return <Card><CardHeader><CardTitle className="text-success">Billing & usage</CardTitle></CardHeader><CardContent className="space-y-7"><div className="rounded-lg border border-border bg-surface2 px-4 py-4"><p className="text-sm font-medium text-ink">Early access</p><p className="mt-1 text-sm text-muted">You have full access while LaunchBench billing is being set up. Your plan and invoices will appear here.</p></div><div><p className="text-sm font-medium text-ink">This month</p><p className="mt-1 text-sm text-muted">A clear record of the work your agents have completed.</p><dl className="mt-4 grid gap-3 sm:grid-cols-3">{stats.map((stat) => <div key={stat.label} className="rounded-lg border border-border px-4 py-4"><dt className="text-sm text-muted">{stat.label}</dt><dd className="mt-1 text-2xl font-semibold text-ink-strong">{stat.value}</dd></div>)}</dl></div></CardContent></Card>;
}
