-- Fix the product foreign keys on ops_events and ops_tasks.
--
-- Both were declared as:
--   foreign key (product_id, workspace_id) references products(id, workspace_id)
--     on delete set null
--
-- A bare SET NULL nulls *every* referencing column, and workspace_id is NOT NULL,
-- so deleting a product that still had tasks or events attached failed with a
-- not-null violation instead of detaching them. The composite reference is worth
-- keeping -- it is what guarantees a row's project lives in its own workspace --
-- so the fix is to name the column that may be nulled, which Postgres 15 added:
--   on delete set null (product_id)
--
-- The constraint is found by what it references rather than by name, because a
-- name generated by the original CREATE TABLE is an implementation detail and
-- guessing it wrong would fail halfway through. Re-running is harmless: it drops
-- and recreates the same constraint with the same definition.

do $$
declare
  target record;
begin
  for target in
    select cls.relname as table_name, con.conname as constraint_name
    from pg_constraint con
    join pg_class cls on cls.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = cls.relnamespace
    where nsp.nspname = 'public'
      and cls.relname in ('ops_events', 'ops_tasks')
      and con.contype = 'f'
      and con.confrelid = 'public.products'::regclass
  loop
    execute format('alter table public.%I drop constraint %I', target.table_name, target.constraint_name);
    execute format(
      'alter table public.%I add constraint %I foreign key (product_id, workspace_id) '
      'references public.products(id, workspace_id) on delete set null (product_id)',
      target.table_name,
      target.constraint_name
    );
    raise notice 'Repaired % on %', target.constraint_name, target.table_name;
  end loop;
end $$;

-- Both tables must now report "SET NULL (product_id)" rather than "SET NULL".
select cls.relname as table_name, con.conname as constraint_name, pg_get_constraintdef(con.oid) as definition
from pg_constraint con
join pg_class cls on cls.oid = con.conrelid
join pg_namespace nsp on nsp.oid = cls.relnamespace
where nsp.nspname = 'public'
  and cls.relname in ('ops_events', 'ops_tasks')
  and con.contype = 'f'
  and con.confrelid = 'public.products'::regclass
order by cls.relname;
